services:
  nestjs-api-prod: 
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=PRODUCTION
    volumes:
      - ./src:/usr/src/app/src  